### ISSUE TITLE
Remover hack de prefetch de imagem 

### ISSUE THREAD

**Issue by jonataspinto** [estartando-devs/site#124]
No global styles tem essa hack para fazer cache da imagem do header, como estamos com uma webp, não precisamos mais disso.

Remover 
```
 ​   content:url("header-bg.png") ;
```

**Comment by jonataspinto** [comment]
@ramonxm pq fechou? Ainda nao foi solucionado

**Comment by jonataspinto** [comment]
Putz, foi mal! foi sim mas ainda não foi para prod

**Comment by ramonxm** [comment]
Tu tinha removido no seu último pr
