### ISSUE TITLE
Correção em títulos de seção nossos resultados.

### ISSUE THREAD

**Issue by jonataspinto** [estartando-devs/site#217]
O problema:

![image](https://github.com/user-attachments/assets/74503648-6ff0-4d12-92e3-9785e4852078)

Essa seção está com o titulo incompleto e os resultados poderiam estar dentro de um `<h3>`
![image](https://github.com/user-attachments/assets/88fee1bf-5d59-457c-93c8-987fd049de28)

Correção:

- Garantir que dentro do `<h2>` tenha o título completo: `Nossos Resultados`
- Colocar os resultados dentro de um `<h3>`

![image](https://github.com/user-attachments/assets/b2b7b7e5-1508-49fb-aba0-40d74b26cec8)

**Comment by jonataspintoafya** [comment]
Ferramenta para teste
https://seo-extension.com/
