### ISSUE TITLE
Adicionar generators 

### ISSUE THREAD

**Issue by jonataspinto** [estartando-devs/site#26]
O que usaremos? PlopJs??
 
Olha essa [opção](https://marketplace.visualstudio.com/items?itemName=asbjornh.vscode-module-templates), parece bacana.

@yagovaluchedevs @ramonxm @joaoprferreira

**Comment by ramonxm** [comment]
Interessante,  menos uma dependência 😅😅

**Comment by ramonxm** [comment]
como ngm comentou, adicionei aquele mr lá que tinha falado.
