### ISSUE TITLE
Ajuste em ação de `Ver módulos`

### ISSUE THREAD

**Issue by jonataspinto** [estartando-devs/site#50]
![image](https://user-images.githubusercontent.com/34426836/156037002-18feacbe-d36f-451a-899e-e3c41e721407.png)

https://github.com/estartando-devs/site/blob/73662c63691c8eb3bb86afe39a87a6f43b3272a2/src/components/Courses/index.tsx#L31

Estava fazendo uma navegação por `tab` e não consegui disparar essa ação pois está em uma imagem. Acho que podemos usar um botão e trazer semântica para esse componente. O que acham?

@yagovaluchedevs @ramonxm @joaoprferreira @henriquecalenzoo

**Comment by ramonxm** [comment]
Pra mim faz sentido

**Comment by ramonxm** [comment]
alguém vai tocar isso? @jonataspinto

**Comment by alanaraujop** [comment]
Fica a vontade @ramonxm .. é tudo nosso

**Comment by ramonxm** [comment]
Já corrigido, fechando a issue.
