### ISSUE TITLE
Usar elementos de lista em listagem de módulos.

### ISSUE THREAD

**Issue by jonataspinto** [estartando-devs/site#75]
Percebi que estamos usando o elemento `<div>` com `<p>` para desenhar essa lista, acho que podemos usar uma lista.

E uma outra sugestão é ver a possibilidade de deixarmos essa lista ja no dom, e alterarmos apenas seu tamanho.

![image](https://user-images.githubusercontent.com/34426836/157156819-5841cdad-0fb7-4f94-97d4-c4487959bc37.png)

**Comment by ramonxm** [comment]
Boa, uma alternativa também porém precisa ver se é viável é utilizar o `details` do html.

Exemplo:

```html
<details>
  <summary>Alguns detalhes</summary>
  <p>Mais informações sobre os detalhes.</p>
</details>

```

**Comment by jonataspinto** [comment]
> Boa, uma alternativa também porém precisa ver se é viável é utilizar o `details` do html.
> 
> Exemplo:
> 
> ```html
> <details>
>   <summary>Alguns detalhes</summary>
>   <p>Mais informações sobre os detalhes.</p>
> </details>
> 
> ```

Verdade, não me recordava desse elemento
