### ISSUE TITLE
Implementar Next SEO para indexação do Google

### ISSUE THREAD

**Issue by ramonxm** [estartando-devs/site#78]
Adicionar SEO Config e manifest.json para indentar nos mecanismos de busca do Google

Ref:
https://github.com/garmeeh/next-seo

**Comment by jonataspinto** [comment]
![image](https://user-images.githubusercontent.com/34426836/157306010-836b1716-dfc6-495c-b854-7c5b254cd0c4.png)

Está meio zoado mesmo
